name: pymc-extras
channels:
- conda-forge
- nodefaults
dependencies:
  - scikit-learn
  - better-optimize>=0.3.2
  - dask<2025.1.1
  - xhistogram
  - statsmodels
  - numba
  - pytest
  - pytest-cov
  - pydantic>=2.0.0
  - h5netcdf
  - pip
  - pip:
      - jax
      - blackjax
      - pymc @ git+https://github.com/pymc-devs/pymc.git
      - preliz @ git+https://github.com/arviz-devs/preliz.git
