name: pymc-extras
channels:
- conda-forge
- nodefaults
dependencies:
  - scikit-learn
  - better-optimize>=0.4.2,<1.0
  - dask<2025.1.1
  - xhistogram
  - statsmodels
  - numba
  - pytest
  - pytest-cov
  - pydantic>=2.0.0,<3.0
  - h5netcdf
  - pymc>=6.2.0,<6.3
  - pytensor>=3.2.3,<3.3
  - arviz>=1.2,<2.0
  - preliz>=0.27,<0.28
  - pip
  - pip:
      - jax
      - blackjax
