name: pymc-extras
channels:
- conda-forge
- nodefaults
dependencies:
  - scikit-learn
  - better-optimize>=0.4.1
  - dask<2025.1.1
  - xhistogram
  - statsmodels
  - numba
  - pytest
  - pytest-cov
  - pydantic>=2.0.0
  - h5netcdf
  - pymc>=6.0,<7.0
  - pip
  - pip:
      - jax
      - blackjax
      - preliz>=0.25
